import type { Metadata } from "next";
import Footer from "./components/Footer/footer";
import "./globals.css";
import Header from "./components/Header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        <main className="w-full">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
